- ProjectSummary.md
I think this is about as good as it can get until we get more info from the Prof. Obv if we decide to pivot project ideas before 1800EDT 23OCT23, we can modify this.
Closes #4
> Add project summary documentation

- .github/workflows/development.yml
- .gitignore
Fixing the workflow to only run on PRs
#29
> Merge dev to main

- tests/test_frontend.py
> deleted duplicate test

- .github/workflows/development.yml
- ProjectSummary.md
- functions/n1_Network_Tool.py
> update projectSummary and pylint rules

- TestPlan.md
> 44 create test plan

- tests/test_frontend.py
Now checks for table data's existence only, not specific values.
> Modified subnet scanner test

- functions/n1_Network_Tool.py
- tests/test_frontend.py
Added HTTP header tool and associated unit test.
Closes #16
> 16 http header tool

- Docker/Dockerfile
- Docker/docker-compose.yml
- functions/n1_Network_Tool.py
- requirements.txt
- Updated to Streamlit 1.28.2
- Fixed catch warnings in certificate_lookup() and dns_lookup()
- Fixed non-zero exit-status on subprocess run in certificate_lookup()
- Added traceroute visualization, works with enter key
> 5 traceroute visualizer

- functions/n1_Network_Tool.py
Fixed issue preventing subnet calculator from working with IPs that didn't end in 0.
Resolves #59
> Bug in Subnet Calculator

- tests/test_frontend.py
Draft PR to see if tests pass.
Will resolve issue of subnet scanner tests skipping ahead and looking for output before there is any.
Resolves #60
> 60 fix subnet scan failing test

- Home.py
- functions/n1_Network_Tool.py
- requirements.txt
- tests/test_frontend.py
Additionally: 
- Removed a TODO that was completed
- Auto-formatted some of the functions in frontend and n1
Closes #24
> added whois function and tests

- CurrentProjectStatus.md
- ProjectSummary.md
- TestPlan.md
- tests/test_frontend.py
Note: we have #62 open for wget so I marked that as complete. ~We are still waiting for @Rey41888  to submit a PR for #17~
Edit: #17 was closed. Will update the branch once we decide what's going to replace the two features.
> Update living documents

- tests/test_frontend.py
The special character wasn't required. Removed it just to be safe.
> removed special character

- CurrentProjectStatus.md
- ProjectSummary.md
- TestPlan.md
- tests/test_frontend.py
- includes auto-formatting changes. Sorry for the readability
> changed wget to curl throughout

- README.md
Subnet Scanner
HTTP Header Tool
Website Ping
> Added user guides for my tools

- tests/test_frontend.py
Draft PR to see exactly how test fails.
> Fix Subnet Scanner failing Firefox map test

- functions/n1_Network_Tool.py
- tests/test_frontend.py
> url encoder and auto-formatting

- CurrentProjectStatus.md
- FinalReport.md
- ProjectSummary.md
- README.md
- TestPlan.md
- tests/test_frontend.py
Closes #11 
Feel free to request changes to anything you'd like to see modified.
> 11 assemble final report

- tests/test_frontend.py
IP geolocation/what is my IP? test complete. Checking for GitHub failure.
> Add test cases to IP geolocation

- tests/test_frontend.py
Password generator tests pass locally. Making sure they pass on GitHub.
> Add test cases to password generator
